name: Validate pull request before merge

on:
  pull_request:
    branches:
      - master

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle (skip tests)
        run: ./gradlew build -x test

      - name: Perform tests
        run: ./gradlew test